repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=60000"] # max 60MB
      - id: check-merge-conflict
      - id: fix-encoding-pragma

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort
        pass_filenames: false
        always_run: true
        args: [pyproject.toml, --all, --in-place]
        types: [python]

  - repo: https://github.com/myint/docformatter
    rev: 06907d0
    hooks:
      - id: docformatter
        args:
          [
            '--in-place',
            '--pre-summary-newline',
            '--wrap-descriptions=88',
            '--wrap-summaries=88',
          ]
        types: [python]


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^(tests/|node_modules/|venv/)

      - id: ruff-format
        args: [--line-length=88]
        exclude: ^(tests/|node_modules/|venv/)
